### ISSUE TITLE
Mobile Landscape mode

### ISSUE THREAD

**Issue by HiImLen** [lukakldiashvili/Unified-Universal-Blur#3]
I'm currently using your Unified-Universal-Blur and it works great on desktop.
But when I build and test on Android in Landscape mode (both in Landscape left and right), the blur is still in Portrait mode (default not upside down).

**Comment by lukakldiashvili** [comment]
@HiImLen I have tested base configuration on Android Emulator and iOS device, could not notice what could be a problem.
Can you describe how to replicate the problem, and maybe attach an image (probably a link) to outline the problem.

**Comment by HiImLen** [comment]
I don't know how to recreate the problem since I just built the game into an APK and installed it on my Android phone. Here is a record of the problem along with my configuration.

https://github.com/lukakldiashvili/Unified-Universal-Blur/assets/87873614/2d70c218-6139-40ed-90a0-40bd374179bf

**Comment by lukakldiashvili** [comment]
That's perfect, I'll do my best to replicate and find the problem. I will keep you posted.

**Comment by lukakldiashvili** [comment]
Needs further investigation, but I was able to replicate the behaviour with Unity 2021.3 (2022.2 seems to have no problem)

**Comment by lukakldiashvili** [comment]
This bug should be fixed in new release (0.2.0). Problem was caused by using RTHandles in Unity versions lower than 2022. Thank you for opening this issue and I'm looking forward to the feedback.

**Comment by HiImLen** [comment]
It seems like the problem is still persisting in the build that is installed on **actual phones**.
Both versions 0.1.2 and 0.2 have the orientation bug. I also created a new project and imported the latest release but still encountered the same problem.

As for the **emulator** (I used NoxPlayer), when I tried the 0.1.2 version on the Android emulator, it worked fine.
However, version 0.2 doesn't blur (it still hides other UI beneath it).
